#ifndef VOICEENGINE_VERSION_H
#define VOICEENGINE_VERSION_H

#define VOICEENGINE_VERSION_MAJOR 0
#define VOICEENGINE_VERSION_MINOR 1
#define VOICEENGINE_VERSION_PATCH 0
#define VOICEENGINE_API_VERSION 1

#define VOICEENGINE_VERSION_STRING "0.1.0"

#endif
