set(SCANENGINE_CORE_SOURCES
    src/core/ui_options.cpp
    src/core/models.cpp
    src/core/strict_json.cpp
    src/core/output_layout.cpp
    src/core/config.cpp
    src/core/preprocess.cpp
    src/core/markdown_preview.cpp
    src/core/excel_export.cpp
    src/core/parser_service.cpp
    src/hybrid/rounding.cpp
    src/hybrid/orchestrator.cpp
    src/hybrid/vlm_paths.cpp
    src/hybrid/vlm_config.cpp
    src/hybrid/safetensors.cpp
    src/gpu/gpu_weight_store.cpp
    src/hybrid/vlm_weights.cpp
    src/hybrid/prompts.cpp
    src/hybrid/preprocessor.cpp
    src/hybrid/tokenizer.cpp
    src/hybrid/chat.cpp
    src/hybrid/embed.cpp
    src/hybrid/qwen2_language.cpp
    src/hybrid/qwen2_vision.cpp
    src/hybrid/qwen2_vl.cpp
    src/hybrid/canonical_generation.cpp
    src/hybrid/canonical_model.cpp
    src/hybrid/official_post_process.cpp
    src/hybrid/official_code_language.cpp
    src/hybrid/official_language_detection.cpp
    src/hybrid/table_image_processor.cpp
    src/hybrid/extract.cpp
    src/hybrid/layout.cpp
    src/hybrid/layout_v2.cpp
    src/hybrid/ocr.cpp
    src/hybrid/ocr_ppv6.cpp
    src/hybrid/otsl.cpp
    src/hybrid/official_page.cpp
    src/hybrid/device_policy.cpp
    include/scanengine/parser_service.hpp)
