#ifndef SCANENGINE_VERSION_H
#define SCANENGINE_VERSION_H

#define SCANENGINE_VERSION_MAJOR 0
#define SCANENGINE_VERSION_MINOR 1
#define SCANENGINE_VERSION_PATCH 0
#define SCANENGINE_API_VERSION 1
#define SCANENGINE_VERSION_STRING "0.1.0"

#endif
